module.exports = {
	apps: [
		{
			name: "posters",
			script: "./bin/www",
			watch: true,
			ignore_watch: ["node_modules", "public", "logs"],
			env_local: {
				PORT: 7000,
				NODE_ENV: "local",
				DOMAIN_URL: "http://127.0.0.1:7000",
				DB_MONGO_URL:
					"mongodb+srv://devstree:devstree@posters.izq95.mongodb.net/posters?retryWrites=true&w=majority",
				JWT_SECRET: "jsonwebtoken",
				SMTP_PORT: 587,
				SMTP_HOST: "smtp.gmail.com",
				SMTP_SECURE_CONNECTION: "",
				SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
				SMTP_AUTH_PASSWORD: "nhnsbescnaenruqk",
				SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
			},
			env: {
				PORT: 7000,
				NODE_ENV: "local",
				DOMAIN_URL: "http://127.0.0.1:7000",
				DB_MONGO_URL:
					"mongodb+srv://devstree:devstree@posters.izq95.mongodb.net/posters?retryWrites=true&w=majority",
				JWT_SECRET: "jsonwebtoken",
				SMTP_PORT: 587,
				SMTP_HOST: "smtp.gmail.com",
				SMTP_SECURE_CONNECTION: "",
				SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
				SMTP_AUTH_PASSWORD: "nhnsbescnaenruqk",
				SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
			},
			env_production: {
				PORT: 7000,
				NODE_ENV: "local",
				DOMAIN_URL: "http://3.111.177.73:7000",
				DB_MONGO_URL: "mongodb://localhost:27017/sirqil",
				JWT_SECRET: "jsonwebtoken",
				SMTP_PORT: 587,
				SMTP_HOST: "smtp.gmail.com",
				SMTP_SECURE_CONNECTION: "",
				SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
				SMTP_AUTH_PASSWORD: "nhnsbescnaenruqk",
				SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
			},
			env_staging: {
				PORT: 7000,
				NODE_ENV: "local",
				DOMAIN_URL: "http://172.105.35.50:7000",
				DB_MONGO_URL:
					"mongodb+srv://devstree:devstree@posters.izq95.mongodb.net/posters?retryWrites=true&w=majority",
				JWT_SECRET: "jsonwebtoken",
				SMTP_PORT: 587,
				SMTP_HOST: "smtp.gmail.com",
				SMTP_SECURE_CONNECTION: "",
				SMTP_AUTH_USER: "smtp.devstree2020@gmail.com",
				SMTP_AUTH_PASSWORD: "nhnsbescnaenruqk",
				SMTP_SOURCE_EMAIL: "smtp.devstree2020@gmail.com",
			},
		},
	],
};
